# ------------- motion ---------------
[motion]
arc_unit_length = 1.0
feedrate = 0.0
positioning = "absolute"
feedrate_multiplier = 1

[motion.retraction]
feedrate = 0.0
length = 0.0
z_lift = 0.0

[motion.recover]
feedrate = 0.0
length = 0.0

[motion.endstops.x]
pin = "PF0"
exti = "EXTI0"

[motion.endstops.y]
pin = "PF1"
exti = "EXTI1"

[motion.endstops.z]
pin = "PF2"
exti = "EXTI2"

# ------------- steppers ---------------

[steppers.x]
stepping_mode = "full"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = -200
bounds.max = 200
positive_direction = "counterclockwise"
step.pin = "PC11"
dir.pin = "PC10"

[steppers.y]
stepping_mode = "full"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = -200
bounds.max = 200
positive_direction = "counterclockwise"
step.pin = "PC9"
dir.pin = "PC8"

[steppers.z]
stepping_mode = "full"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = 0
bounds.max = 200
positive_direction = "clockwise"
step.pin = "PD2"
dir.pin = "PC12"

[steppers.e]
stepping_mode = "full"
distance_per_step = 0.1
steps_per_revolution = 200
bounds.min = 0
bounds.max = 0
positive_direction = "counterclockwise"
step.pin = "PG2"
dir.pin = "PG3"

# ------------- uart ---------------

[uart]
peripheral="UART4"
baudrate=19800
rx.pin = "PB8"
rx.dma.peripheral = "DMA1_CH0"
tx.pin = "PB9"
tx.dma.peripheral = "DMA1_CH1"

# ------------- pwm --------------
[pwm]
frequency = 0
timer = "TIM2"
ch1 = "PA0"
ch2 = "PB3"
ch3 = "PB10"

# ------------- hotend ---------------

[hotend.heater]
pwm.channel = 1
max_temperature_limit=200
min_temperature_limit=200

[hotend.heater.pid]
k_p = 0
k_i = 0
k_d = 0

[hotend.thermistor]
r_series=0
r0=0
b = 0
samples = 0

[hotend.thermistor.adc]
peripheral = "ADC1"
input.pin = "PA5"
dma.peripheral = "DMA1_CH2"

# ------------- heatbed ---------------

[heatbed.heater]
pwm.channel = 2
max_temperature_limit=200
min_temperature_limit=200

[heatbed.heater.pid]
k_p = 0
k_i = 0
k_d = 0


[heatbed.thermistor]
r_series=0
r0=0
b = 0
samples = 0

[heatbed.thermistor.adc]
peripheral = "ADC2"
input.pin = "PA6"
dma.peripheral = "DMA1_CH3"

# ------------- fan ---------------

[fan]
max_speed = 10000

[fan.pwm]
channel = 3

# ------------- sdcard ---------------

[sdcard.spi]
peripheral = "SPI2"

[sdcard.spi.clk]
peripheral = "PD3"

[sdcard.spi.mosi]
pin = "PC3"

[sdcard.spi.miso]
pin = "PC2"

[sdcard.spi.cs]
pin = "PD7"
