# ------------- motion ---------------
[motion]
arc_unit_length = 1.0
feedrate = 0.0
positioning = "absolute"
e_positioning = "absolute"
feedrate_multiplier = 1

[motion.retraction]
feedrate = 0.0
length = 0.0
z_lift = 0.0

[motion.recover]
feedrate = 0.0
length = 0.0

[motion.endstops.x]
pin = "PF0"
exti = "EXTI0"

[motion.endstops.y]
pin = "PF1"
exti = "EXTI1"

[motion.endstops.z]
pin = "PF2"
exti = "EXTI2"

# ------------- steppers ---------------

[steppers.x]
stepping_mode = "half"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = -100
bounds.max = 100
positive_direction = "counterclockwise"
step.pin = "PC11"
dir.pin = "PC10"

[steppers.y]
stepping_mode = "half"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = -100
bounds.max = 100
positive_direction = "counterclockwise"
step.pin = "PC9"
dir.pin = "PC8"

[steppers.z]
stepping_mode = "half"
distance_per_step = 0.15
steps_per_revolution = 200
bounds.min = 0
bounds.max = 200
positive_direction = "clockwise"
step.pin = "PD2"
dir.pin = "PC12"

[steppers.e]
stepping_mode = "half"
distance_per_step = 0.1
steps_per_revolution = 200
bounds.min = -5000000
bounds.max = 5000000
positive_direction = "counterclockwise"
step.pin = "PG2"
dir.pin = "PG3"

# ------------- uart ---------------

[uart]
peripheral="UART4"
baudrate = 38400
rx.pin = "PB8"
rx.dma.peripheral = "DMA1_CH0"
tx.pin = "PB9"
tx.dma.peripheral = "DMA1_CH1"

# ------------- pwm --------------
[pwm]
frequency = 0
timer = "TIM3"
ch1 = "PC6"
ch2 = "PC7"
ch3 = "PB0"

# ------------- adc ----------------

[adc]
peripheral = "ADC1"
dma.peripheral = "DMA1_CH2"

# ------------- hotend ---------------

[hotend.heater]
pwm.channel = 1
max_temperature_limit=240
min_temperature_limit=180

[hotend.heater.pid]
k_p = 400
k_i = 5
k_d = 1

[hotend.thermistor]
r_series = 10000
r0 = 100000
b = 3676.85
samples = 5
adc.pin = "PA5"

# ------------- heatbed ---------------

[heatbed.heater]
pwm.channel = 2
max_temperature_limit=240
min_temperature_limit=180

[heatbed.heater.pid]
k_p = 400
k_i = 5
k_d = 1

[heatbed.thermistor]
r_series = 10000
r0 = 100000
b = 3676.85
samples = 5
adc.pin = "PA6"

# ------------- fan ---------------

[fan]
max_speed = 10000

[fan.pwm]
channel = 3

# ------------- sdcard ---------------

[sdcard.spi]
peripheral = "SPI3"

[sdcard.spi.clk]
peripheral = "PB3"

[sdcard.spi.mosi]
pin = "PB5"

[sdcard.spi.miso]
pin = "PB4"

[sdcard.spi.cs]
pin = "PA4"
