[package]
name = "rusty-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.7.3"
cortex-m = "0.7.7"
cortex-m-semihosting = "0.5.0"

panic-halt = "0.2"

[profile.dev]
debug = true

[profile.release]
debug = true
lto = true
opt-level = "s"