[package]
name = "stepper"
version = "0.1.0"
edition = "2021"

[dependencies]
math = { path = "../math" }
futures = { version = "0.3.17", default-features = false, features = ["async-await"] }

[dev-dependencies]
tokio = {version= "1.37.0", features = ["full"]}
approx = {version="0.5.1"}
