# ------------- motion ---------------
[motion]
arc_unit_length = 0.0
feedrate = 0.0
positioning = "absolute"

[motion.retraction]
feedrate = 0.0
length = 0.0
z_lift = 0.0

[motion.recover]
feedrate = 0.0
length = 0.0

[motion.endstops]
x.pin = "PB6"
y.pin = "PB7"
z.pin = "PB8"

# ------------- steppers ---------------

[steppers.x]
stepping_mode = "full"
distance_per_step = 1
steps_per_revolution = 200
bounds = [-10, 10]
positive_direction = "clockwise"

[steppers.x.step]
pin = "PA0"

[steppers.x.dir]
pin = "PA1"

[steppers.y]
stepping_mode = "full"
distance_per_step = 1
steps_per_revolution = 200
bounds.min = -10
bounds.max = 10
positive_direction = "clockwise"

[steppers.y.step]
pin = "PA12"

[steppers.y.dir]
pin = "PA10"

[steppers.z]
stepping_mode = "full"
distance_per_step = 1
steps_per_revolution = 200
bounds = [-10, 10]
positive_direction = "clockwise"

[steppers.z.step]
pin = "PA4"

[steppers.z.dir]
pin = "PA5"

[steppers.e]
stepping_mode = "full"
distance_per_step = 1
steps_per_revolution = 200
bounds = [-10, 10]
positive_direction = "clockwise"

[steppers.e.step]
pin = "PA6"

[steppers.e.dir]
pin = "PA7"

# ------------- uart ---------------

[uart]
peripheral="UART4"
baudrate=19800

[uart.rx]
pin="PA8"

[uart.rx.dma]
peripheral="DMA1_CH0"

[uart.tx]
pin="PA9"

[uart.tx.dma]
peripheral="DMA1_CH1"

# ------------- pwm --------------
[pwm]
frequency = 0
timer = "TIM2"
ch1 = "PA11"
ch2 = "PA13"
ch3 = "PA14"

# ------------- hotend ---------------

[hotend.heater]
r_series=0
r0=0
b = 0
max_temperature_limit=200
min_temperature_limit=200

[hotend.heater.pid]
k_p = 0
k_i = 0
k_d = 0

[hotend.adc]
peripheral = "ADC1"

[hotend.adc.input]
pin = "PA3"

[hotend.adc.dma]
peripheral = "DMA1_CH2"

[hotend.pwm]
channel = 1

# ------------- heatbed ---------------

[heatbed.heater]
r_series=0
r0=0
b = 0
max_temperature_limit=200
min_temperature_limit=200

[heatbed.heater.pid]
k_p = 0
k_i = 0
k_d = 0

[heatbed.adc]
peripheral = "ADC2"

[heatbed.adc.input]
pin = "PA2"

[heatbed.adc.dma]
peripheral = "DMA1_CH3"

[heatbed.pwm]
channel = 2

# ------------- fan ---------------

[fan.pwm]
channel = 3

# ------------- sdcard ---------------

[sdcard.spi]
peripheral = "SPI1"

[sdcard.spi.clk]
peripheral = "PB3"

[sdcard.spi.mosi]
pin = "PB5"

[sdcard.spi.miso]
pin = "PB4"

[sdcard.spi.cs]
pin = "PC12"
