# ------------- steppers ---------------

[steppers.x.step]
pin = "PA0"

[steppers.x.dir]
pin = "PA1"

[steppers.y.step]
pin = "PA2"

[steppers.y.dir]
pin = "PA3"

[steppers.z.step]
pin = "PA4"

[steppers.z.dir]
pin = "PA5"

[steppers.e.step]
pin = "PA6"

[steppers.e.dir]
pin = "PA7"

# ------------- uart ---------------

[uart]
peripheral="UART4"
baudrate=19800

[uart.rx]
pin="PA8"

[uart.rx.dma]
peripheral="DMA1_CH0"

[uart.tx]
pin="PA9"

[uart.tx.dma]
peripheral="DMA1_CH1"

# ------------- pwm --------------
[pwm]
frequency = 0
timer = "TIM2"

# ------------- hotend ---------------

[hotend.heater]
r_series=0
r0=0
b = 0

[hotend.heater.pid]
k_p = 0
k_i = 0
k_d = 0

[hotend.adc]
peripheral = "ADC1"

[hotend.adc.input]
pin = "PA10"

[hotend.adc.dma]
peripheral = "DMA1_CH2"

[hotend.pwm]
output = "PA11"
channel = 1

# ------------- heatbed ---------------

[heatbed.heater]
r_series=0
r0=0
b = 0

[heatbed.heater.pid]
k_p = 0
k_i = 0
k_d = 0

[heatbed.adc]
peripheral = "ADC2"

[heatbed.adc.input]
pin = "PA12"

[heatbed.adc.dma]
peripheral = "DMA1_CH3"

[heatbed.pwm]
output = "PA13"
channel = 2

# ------------- fan ---------------

[fan.pwm]
output = "PA14"
channel = 3

# ------------- sdcard ---------------

[sdcard.spi]
peripheral = "SPI1"

[sdcard.spi.timer]
peripheral = "TIM5"

[sdcard.spi.mosi]
pin = "PB0"

[sdcard.spi.miso]
pin = "PB1"

[sdcard.spi.cs]
pin = "PB2"
