[package]
name = "fan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
measurements = {version="0.11.0", default-features=false}

[dev-dependencies]
approx = {version="0.5.1"}
