[target.thumbv7em-none-eabihf]
rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tdefmt.x"
]
runner = "probe-run --chip STM32H753ZITx"

[build]
target = "thumbv7em-none-eabihf"
