[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32H753ZITx'

[build]
target = "thumbv7em-none-eabihf"
rustflags=[
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    "-Z", "emit-stack-sizes",
]

[env]
DEFMT_LOG = "trace"
